---
- name: Install,uninstall,update multiple s/w apps
  hosts: all
  tasks:
    - name: Install s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: git,b: present,c: no}
        - {a: maven,b: absent,c: no}
        - {a: openjdk-17-jdk,b: latest,c: yes}

...


