---
- name: Create multiple users and copy files into the users home dirs
  hosts: all
  tasks:
    - name: Create multiple users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: vinay,b: reddy,c: /tmp/vinay}
        - {a: anu,b: reddy,c: /home/anu}
    - name: Copy files into users home dirs
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /tmp/vinay}
        - {a: /etc/group,b: /home/anu}
...

