---
- name: Install tree on Ubuntu servers
  hosts: ubuntu
  tasks:
    - name: Install tree 
      apt:
        name: tree
        state: present
        update_cache: yes

- name: Install tree on RedHat servers
  hosts: redhat
  tasks:
    - name: Install tree 
      yum:
        name: tree
        state: present
        update_cache: yes


